[mcp_servers.msw-maker-mcp]
command = "cmd.exe"
args = ["/c", "call", "C:\\Nexon\\MapleStory Worlds\\MakerMCP\\msw-maker-mcp.bat"]

[mcp_servers.msw-mcp]
url = "https://msw-mcp.nexon.com/mcp"
http_headers = { "Authorization" = "Bearer e676ea6e62f546b8925a66318bbf8cf0" }
